name: "Build"
on: [push, pull_request]

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - name: checkout
        uses: actions/checkout@v2
      - name: lint
        run: make lint
  test:
    name: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - name: checkout
        uses: actions/checkout@v2
      - name: install hwdata -yq
        run: sudo apt-get install hwdata -yq
      - name: test
        run: make test-coverage
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: '1.13'
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: make build